handlers:
  - sink: ext://sys.stdout
    level: DEBUG
    format: "|<level>{level: <8}</level>| <magenta>{name}</magenta>:<bold>{function}</bold>:<magenta>{line}</magenta> |  <level>{message}</level> | <l>{extra}</>"
    enqueue: true
    colorize: true
    diagnose: true
    backtrace: true
  # - sink: logs/application.log
  #   level: INFO
  #   format: "<level>{level}</level>:<cyan>{message}</cyan> | {extra}"
  #   serialize: true
  #   retention: 7 days
  #   diagnose: false
  #   backtrace: true
  #   enqueue: true

activation:
  - ["my_module.secret", false]
  - ["another_library.module", true]
