"""deleteing member is_deleted flag for simplicity

Revision ID: 79ef44838e1b
Revises: fd8e56e20661
Create Date: 2025-08-20 15:23:58.651471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ef44838e1b'
down_revision: Union[str, Sequence[str], None] = 'fd8e56e20661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_is_deleted_flag'), table_name='members')
    op.drop_column('members', 'is_deleted_flag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('is_deleted_flag', sa.BOOLEAN(), nullable=False))
    op.create_index(op.f('ix_members_is_deleted_flag'), 'members', ['is_deleted_flag'], unique=False)
    # ### end Alembic commands ###
