"""pemisah concern logika data dan logika bussines

Revision ID: 99523b9b74da
Revises: a9741e8af6e4
Create Date: 2025-08-19 20:09:29.870393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99523b9b74da'
down_revision: Union[str, Sequence[str], None] = 'a9741e8af6e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('memberid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ipaddress', sa.String(length=45), nullable=False),
    sa.Column('report_url', sa.String(length=2048), nullable=False),
    sa.Column('pin', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('allow_nosign', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('memberid')
    )
    op.create_index(op.f('ix_members_allow_nosign'), 'members', ['allow_nosign'], unique=False)
    op.create_index(op.f('ix_members_created_at'), 'members', ['created_at'], unique=False)
    op.create_index(op.f('ix_members_created_by'), 'members', ['created_by'], unique=False)
    op.create_index(op.f('ix_members_deleted_at'), 'members', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_members_deleted_by'), 'members', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_members_ipaddress'), 'members', ['ipaddress'], unique=False)
    op.create_index(op.f('ix_members_is_active'), 'members', ['is_active'], unique=False)
    op.create_index(op.f('ix_members_is_deleted_flag'), 'members', ['is_deleted_flag'], unique=False)
    op.create_index(op.f('ix_members_memberid'), 'members', ['memberid'], unique=True)
    op.create_index(op.f('ix_members_report_url'), 'members', ['report_url'], unique=False)
    op.create_index(op.f('ix_members_updated_at'), 'members', ['updated_at'], unique=False)
    op.create_index(op.f('ix_members_updated_by'), 'members', ['updated_by'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_by'), 'users', ['created_by'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_by'), 'users', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted_flag'), 'users', ['is_deleted_flag'], unique=False)
    op.create_index(op.f('ix_users_is_superuser'), 'users', ['is_superuser'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_updated_by'), 'users', ['updated_by'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_updated_by'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_is_superuser'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted_flag'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_by'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_by'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_members_updated_by'), table_name='members')
    op.drop_index(op.f('ix_members_updated_at'), table_name='members')
    op.drop_index(op.f('ix_members_report_url'), table_name='members')
    op.drop_index(op.f('ix_members_memberid'), table_name='members')
    op.drop_index(op.f('ix_members_is_deleted_flag'), table_name='members')
    op.drop_index(op.f('ix_members_is_active'), table_name='members')
    op.drop_index(op.f('ix_members_ipaddress'), table_name='members')
    op.drop_index(op.f('ix_members_deleted_by'), table_name='members')
    op.drop_index(op.f('ix_members_deleted_at'), table_name='members')
    op.drop_index(op.f('ix_members_created_by'), table_name='members')
    op.drop_index(op.f('ix_members_created_at'), table_name='members')
    op.drop_index(op.f('ix_members_allow_nosign'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
