"""rubah id jadi id dan int

Revision ID: b0beb4c1537e
Revises: a4867f0a08f5
Create Date: 2025-08-18 20:08:17.739418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0beb4c1537e'
down_revision: Union[str, Sequence[str], None] = 'a4867f0a08f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_column('members', 'id')
    # ### end Alembic commands ###
