"""unique true pada memberid

Revision ID: cd69763a449e
Revises: b0beb4c1537e
Create Date: 2025-08-18 20:19:57.062631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd69763a449e'
down_revision: Union[str, Sequence[str], None] = 'b0beb4c1537e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_memberid'), table_name='members')
    op.create_index(op.f('ix_members_memberid'), 'members', ['memberid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_memberid'), table_name='members')
    op.create_index(op.f('ix_members_memberid'), 'members', ['memberid'], unique=False)
    # ### end Alembic commands ###
