"""update with timestamp mixin

Revision ID: cebe498ce01c
Revises: cd69763a449e
Create Date: 2025-08-19 12:16:59.061369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cebe498ce01c'
down_revision: Union[str, Sequence[str], None] = 'cd69763a449e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column('members', sa.Column('pin', sa.String(length=255), nullable=False))
    op.add_column('members', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('members', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('members', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_column('members', 'hash_password')
    op.drop_column('members', 'id')
    op.drop_column('members', 'hash_pin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('hash_pin', sa.VARCHAR(length=255), nullable=False))
    op.add_column('members', sa.Column('id', sa.INTEGER(), nullable=False))
    op.add_column('members', sa.Column('hash_password', sa.VARCHAR(length=255), nullable=False))
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.drop_column('members', 'deleted_at')
    op.drop_column('members', 'is_deleted')
    op.drop_column('members', 'password')
    op.drop_column('members', 'pin')
    op.drop_table('users')
    # ### end Alembic commands ###
